### ISSUE TITLE
Allow disabling the root folder

### ISSUE THREAD

**Issue by Managor** [ratibus11/folders2graph#6]
It would be best if it was possible to remove the `/` folder from view as I have no control over that.

**Comment by ratibus11** [comment]
In which cases do you want to be able to remove the `/` node?
When the folder is empty? Anytime? Something else?
Do you have an example of the expected behavior/render?

**Comment by Managor** [comment]
Ah yes, sure.  Here's a screenshot of what I'm talking about. 
![image](https://github.com/Ratibus11/folders2graph/assets/42655600/a9a1897b-d956-4989-8e87-c6715f54e85a)
I am able to delete any folder from the graph and adjust their associations but I can't delete this folder. The notes in the root do not necessarily relate to each other.

**Comment by ssfxate** [comment]
It's very laggy when there is a root folder linked to every its note in a big vault. I don't have all the notes in the folders.
I'm looking for the same option to turn off `/` from the Graph view.

The rest is fantastic. Thank you very much for such a plugin; getting extra links without additional effort is beneficial.

**Comment by ratibus11** [comment]
Hello everyone.
Sorry for having let that issue rot for months. Still have some exams before finishing my studies. I will implement that feature as soon as possible.

**Comment by milotek** [comment]
Hi Ratibus, sorry to ask again do you still plan to continue the development of this plugin? It's fantastic and settings like this and colour customisability for example, would be amazing. Very nice plugin =)

**Comment by ratibus11** [comment]
Hi @pixeljammed and others!
Just working on the setting. It's normally done! I just have to publish it :) !

**Comment by ratibus11** [comment]
> settings like this and colour customisability for example, would be amazing.

For the customization part, as said in #8, I don't find any way to customize nodes, as Obsidian seems not to offer ways to create new kind of nodes or edit the current ones.
If someone finds a way to change that, I'll be pleased to add some magic into the plugin ✨

**Comment by ratibus11** [comment]
The release as been published on the repo.
Feel free to download the build until the plugin is updated on Obsidian!

https://github.com/ratibus11/folders2graph/releases/tag/1.1.0

I'm closing the issue as the feature has been released.

**Comment by ratibus11** [comment]
After many attempts to add some automation to the release workflow, the plugin of officially available on Obsidian!
Enjoy!

*By default, the root node is displayed*
![image](https://github.com/user-attachments/assets/c4ecd2ae-2126-46e7-91dc-53fecd2e1677)

*You can turn off the root node from the plugin settings*
![image](https://github.com/user-attachments/assets/5ce7129d-0801-44db-92b1-466e9e10cac0)
